### ISSUE TITLE
Application server

### ISSUE THREAD

**Issue by tjago** [kito99/polymer-javaee-mvc-todo#1]
Hi Kito,
I wish to know if there is way to run this code on glassfish 4.1.1 or 4.1 ?

I have builded .war file and deployed on newest glassfish 4.1.1 and navigated to gui.
Loggin was piece'o'cake too, but the I received exception and the list of tasks did not displayed

```
java.lang.ClassNotFoundException: javax.xml.parsers.ParserConfigurationException not found by org.eclipse.persistence.moxy [228]
```

with glassfish 4.1 .war it's even worse doesn't deploy,
Maybe I'm missing some vital point, while java ee 7 code and glassfish is quete a new stuff for me.

Any suggestions appreciated.

**Comment by kito99** [comment]
Try it with [Payara 4.1.1.154](http://bit.ly/1S0EEMI).

**Comment by tjago** [comment]
Now it works, thanks for advice Kito :+1:
