### ISSUE TITLE
Are these components server rendered?

### ISSUE THREAD

**Issue by protoEvangelion** [kito99/polymer-javaee-mvc-todo#2]
I didn't see this question answered in the webinar related to this repo, but are these polymer components rendered on the server or the client?

**Comment by kito99** [comment]
Well, the markup is generated on the server, but that markup includes Polymer elements that handle their functionality client-side.  Thee isn't much dynamic content on the server, so you could just say they are rendered client-side.

**Comment by protoEvangelion** [comment]
Got it thanks for the clarification :+1:
